const db = require('./db');

const definitions = {
  runners: {
    id: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    name: 'TEXT NOT NULL',
    token: 'TEXT UNIQUE NOT NULL',
    tracking_enabled: 'BOOLEAN NOT NULL DEFAULT TRUE',
    is_most_wanted: 'BOOLEAN NOT NULL DEFAULT FALSE',
    last_latitude: 'DOUBLE PRECISION',
    last_longitude: 'DOUBLE PRECISION',
    last_accuracy: 'DOUBLE PRECISION',
    last_speed: 'DOUBLE PRECISION',
    last_location_at: 'TIMESTAMPTZ',
    live_latitude: 'DOUBLE PRECISION',
    live_longitude: 'DOUBLE PRECISION',
    live_accuracy: 'DOUBLE PRECISION',
    live_speed: 'DOUBLE PRECISION',
    live_location_at: 'TIMESTAMPTZ',
    penalty_until: 'TIMESTAMPTZ',
    last_hunter_distance_km: 'DOUBLE PRECISION',
    last_hunter_speed: 'DOUBLE PRECISION',
    last_hunter_location_at: 'TIMESTAMPTZ',
    most_wanted_distance_km: 'DOUBLE PRECISION',
    most_wanted_speed: 'DOUBLE PRECISION',
    most_wanted_updated_at: 'TIMESTAMPTZ',
    most_wanted_until: 'TIMESTAMPTZ',
    created_at: 'TIMESTAMPTZ NOT NULL DEFAULT NOW()',
    location_cycle_started_at: 'TIMESTAMPTZ'
  },
  settings: {
    id: 'INTEGER PRIMARY KEY',
    location_interval: 'INTEGER NOT NULL DEFAULT 20',
    distance_enabled: 'BOOLEAN NOT NULL DEFAULT TRUE',
    updated_at: 'TIMESTAMPTZ NOT NULL DEFAULT NOW()',
    game_title: "TEXT NOT NULL DEFAULT 'Most Wanted - A hajsza'",
    game_description: 'TEXT NOT NULL DEFAULT \'A vadászok követik a menekülőket.\'',
    runner_instructions: 'TEXT NOT NULL DEFAULT \'Tartsd nyitva az oldalt és engedélyezd a helymeghatározást.\'',
    announcement: 'TEXT NOT NULL DEFAULT \'A játékhoz tartozó üzenetek itt jelennek meg.\'',
    live_update_interval: 'INTEGER NOT NULL DEFAULT 1',
    speed_enabled: 'BOOLEAN NOT NULL DEFAULT TRUE',
    alerts_enabled: 'BOOLEAN NOT NULL DEFAULT TRUE',
    high_accuracy_enabled: 'BOOLEAN NOT NULL DEFAULT TRUE',
    penalty_enabled: 'BOOLEAN NOT NULL DEFAULT TRUE',
    game_status: "TEXT NOT NULL DEFAULT 'waiting'",
    announcement_priority: "TEXT NOT NULL DEFAULT 'important'",
    accent_color: "TEXT NOT NULL DEFAULT '#9b87f5'",
    most_wanted_mode: "TEXT NOT NULL DEFAULT '1m'",
    most_wanted_active_runner_id: 'BIGINT',
    most_wanted_active_until: 'TIMESTAMPTZ',
    most_wanted_cooldown_until: 'TIMESTAMPTZ'
  },
  locations: {
    id: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    runner_id: 'BIGINT',
    latitude: 'DOUBLE PRECISION NOT NULL',
    longitude: 'DOUBLE PRECISION NOT NULL',
    accuracy: 'DOUBLE PRECISION',
    speed: 'DOUBLE PRECISION',
    created_at: 'TIMESTAMPTZ NOT NULL DEFAULT NOW()'
  },
  messages: {
    id: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    runner_id: 'BIGINT',
    message: 'TEXT NOT NULL',
    priority: "TEXT NOT NULL DEFAULT 'normal'",
    created_at: 'TIMESTAMPTZ NOT NULL DEFAULT NOW()'
  },
  events: {
    id: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    type: 'TEXT NOT NULL',
    runner_id: 'BIGINT',
    data: 'TEXT',
    created_at: 'TIMESTAMPTZ NOT NULL DEFAULT NOW()'
  },
  hunter_presence: {
    id: 'INTEGER PRIMARY KEY',
    latitude: 'DOUBLE PRECISION',
    longitude: 'DOUBLE PRECISION',
    accuracy: 'DOUBLE PRECISION',
    speed: 'DOUBLE PRECISION',
    location_at: 'TIMESTAMPTZ',
    updated_at: 'TIMESTAMPTZ NOT NULL DEFAULT NOW()'
  }
};

async function ensureColumn(table, column, definition) {
  await db.query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${column} ${definition}`);
}

async function ensureSchema() {
  for (const [table, columns] of Object.entries(definitions)) {
    const primary = columns.id;
    const columnSql = Object.entries(columns)
      .map(([column, definition]) => `${column} ${definition}`)
      .join(',\n');
    await db.query(`CREATE TABLE IF NOT EXISTS ${table} (${columnSql})`);
    for (const [column, definition] of Object.entries(columns)) {
      if (column === 'id') continue;
      await ensureColumn(table, column, definition);
    }
  }

  await db.query(`INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING`);
  await db.query(`INSERT INTO hunter_presence (id) VALUES (1) ON CONFLICT (id) DO NOTHING`);
  await db.query(`UPDATE runners SET tracking_enabled = COALESCE(tracking_enabled, TRUE), is_most_wanted = COALESCE(is_most_wanted, FALSE)`);
  await db.query(`UPDATE settings SET location_interval = COALESCE(location_interval, 20), live_update_interval = COALESCE(live_update_interval, 1), distance_enabled = COALESCE(distance_enabled, TRUE), speed_enabled = COALESCE(speed_enabled, TRUE), alerts_enabled = COALESCE(alerts_enabled, TRUE), high_accuracy_enabled = COALESCE(high_accuracy_enabled, TRUE), penalty_enabled = COALESCE(penalty_enabled, TRUE), game_status = COALESCE(game_status, 'waiting'), announcement_priority = COALESCE(announcement_priority, 'important'), accent_color = COALESCE(accent_color, '#9b87f5'), most_wanted_mode = COALESCE(most_wanted_mode, '1m'), updated_at = COALESCE(updated_at, NOW()) WHERE id = 1`);
  await db.query(`UPDATE runners SET is_most_wanted = COALESCE(is_most_wanted, FALSE)`);
}

module.exports = { ensureSchema };
